SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

INSERT INTO `countries` (`id`, `name`, `code`, `phone_code`, `lang_code`, `region`, `created_at`, `updated_at`) VALUES
(1, 'Afghanistan', 'AF', '+93', 'pus', 'Asia', NULL, NULL),
(2, 'Albania', 'AL', '+355', 'sqi', 'Europe', NULL, NULL),
(3, 'Algeria', 'DZ', '+213', 'ara', 'Africa', NULL, NULL),
(4, 'Andorra', 'AD', '+376', 'cat', 'Europe', NULL, NULL),
(5, 'Angola', 'AO', '+244', 'por', 'Africa', NULL, NULL),
(6, 'Argentina', 'AR', '+54', 'spa', 'South America', NULL, NULL),
(7, 'Armenia', 'AM', '+374', 'hye', 'Asia', NULL, NULL),
(8, 'Australia', 'AU', '+61', 'eng', 'Oceania', NULL, NULL),
(9, 'Austria', 'AT', '+43', 'deu', 'Europe', NULL, NULL),
(10, 'Azerbaijan', 'AZ', '+994', 'aze', 'Asia', NULL, NULL),
(11, 'Bahamas', 'BS', '+1', 'eng', 'North America', NULL, NULL),
(12, 'Bahrain', 'BH', '+973', 'ara', 'Asia', NULL, NULL),
(13, 'Bangladesh', 'BD', '+880', 'ben', 'Asia', NULL, NULL),
(14, 'Barbados', 'BB', '+1', 'eng', 'North America', NULL, NULL),
(15, 'Belarus', 'BY', '+375', 'bel', 'Europe', NULL, NULL),
(16, 'Belgium', 'BE', '+32', 'nld', 'Europe', NULL, NULL),
(17, 'Belize', 'BZ', '+501', 'eng', 'North America', NULL, NULL),
(18, 'Benin', 'BJ', '+229', 'fra', 'Africa', NULL, NULL),
(19, 'Bhutan', 'BT', '+975', 'dzo', 'Asia', NULL, NULL),
(20, 'Bolivia', 'BO', '+591', 'spa', 'South America', NULL, NULL),
(21, 'Bosnia and Herzegovina', 'BA', '+387', 'bos', 'Europe', NULL, NULL),
(22, 'Botswana', 'BW', '+267', 'eng', 'Africa', NULL, NULL),
(23, 'Brazil', 'BR', '+55', 'por', 'South America', NULL, NULL),
(24, 'Brunei', 'BN', '+673', 'msa', 'Asia', NULL, NULL),
(25, 'Bulgaria', 'BG', '+359', 'bul', 'Europe', NULL, NULL),
(26, 'Burkina Faso', 'BF', '+226', 'fra', 'Africa', NULL, NULL),
(27, 'Burundi', 'BI', '+257', 'run', 'Africa', NULL, NULL),
(28, 'Cambodia', 'KH', '+855', 'khm', 'Asia', NULL, NULL),
(29, 'Cameroon', 'CM', '+237', 'fra', 'Africa', NULL, NULL),
(30, 'Canada', 'CA', '+1', 'eng', 'North America', NULL, NULL),
(31, 'Cape Verde', 'CV', '+238', 'por', 'Africa', NULL, NULL),
(32, 'Central African Republic', 'CF', '+236', 'fra', 'Africa', NULL, NULL),
(33, 'Chad', 'TD', '+235', 'fra', 'Africa', NULL, NULL),
(34, 'Chile', 'CL', '+56', 'spa', 'South America', NULL, NULL),
(35, 'China', 'CN', '+86', 'zho', 'Asia', NULL, NULL),
(36, 'Colombia', 'CO', '+57', 'spa', 'South America', NULL, NULL),
(37, 'Comoros', 'KM', '+269', 'ara', 'Africa', NULL, NULL),
(38, 'Congo (DRC)', 'CD', '+243', 'fra', 'Africa', NULL, NULL),
(39, 'Congo (Republic)', 'CG', '+242', 'fra', 'Africa', NULL, NULL),
(40, 'Costa Rica', 'CR', '+506', 'spa', 'North America', NULL, NULL),
(41, 'Croatia', 'HR', '+385', 'hrv', 'Europe', NULL, NULL),
(42, 'Cuba', 'CU', '+53', 'spa', 'North America', NULL, NULL),
(43, 'Cyprus', 'CY', '+357', 'ell', 'Europe', NULL, NULL),
(44, 'Czech Republic', 'CZ', '+420', 'ces', 'Europe', NULL, NULL),
(45, 'Denmark', 'DK', '+45', 'dan', 'Europe', NULL, NULL),
(46, 'Djibouti', 'DJ', '+253', 'ara', 'Africa', NULL, NULL),
(47, 'Dominica', 'DM', '+1', 'eng', 'North America', NULL, NULL),
(48, 'Dominican Republic', 'DO', '+1', 'spa', 'North America', NULL, NULL),
(49, 'Ecuador', 'EC', '+593', 'spa', 'South America', NULL, NULL),
(50, 'Egypt', 'EG', '+20', 'ara', 'Africa', NULL, NULL),
(51, 'El Salvador', 'SV', '+503', 'spa', 'North America', NULL, NULL),
(52, 'Equatorial Guinea', 'GQ', '+240', 'spa', 'Africa', NULL, NULL),
(53, 'Eritrea', 'ER', '+291', 'tir', 'Africa', NULL, NULL),
(54, 'Estonia', 'EE', '+372', 'est', 'Europe', NULL, NULL),
(55, 'Eswatini', 'SZ', '+268', 'eng', 'Africa', NULL, NULL),
(56, 'Ethiopia', 'ET', '+251', 'amh', 'Africa', NULL, NULL),
(57, 'Fiji', 'FJ', '+679', 'eng', 'Oceania', NULL, NULL),
(58, 'Finland', 'FI', '+358', 'fin', 'Europe', NULL, NULL),
(59, 'France', 'FR', '+33', 'fra', 'Europe', NULL, NULL),
(60, 'Gabon', 'GA', '+241', 'fra', 'Africa', NULL, NULL),
(61, 'Gambia', 'GM', '+220', 'eng', 'Africa', NULL, NULL),
(62, 'Georgia', 'GE', '+995', 'kat', 'Asia', NULL, NULL),
(63, 'Germany', 'DE', '+49', 'deu', 'Europe', NULL, NULL),
(64, 'Ghana', 'GH', '+233', 'eng', 'Africa', NULL, NULL),
(65, 'Greece', 'GR', '+30', 'ell', 'Europe', NULL, NULL),
(66, 'Grenada', 'GD', '+1', 'eng', 'North America', NULL, NULL),
(67, 'Guatemala', 'GT', '+502', 'spa', 'North America', NULL, NULL),
(68, 'Guinea', 'GN', '+224', 'fra', 'Africa', NULL, NULL),
(69, 'Guinea-Bissau', 'GW', '+245', 'por', 'Africa', NULL, NULL),
(70, 'Guyana', 'GY', '+592', 'eng', 'South America', NULL, NULL),
(71, 'Haiti', 'HT', '+509', 'fra', 'North America', NULL, NULL),
(72, 'Honduras', 'HN', '+504', 'spa', 'North America', NULL, NULL),
(73, 'Hungary', 'HU', '+36', 'hun', 'Europe', NULL, NULL),
(74, 'Iceland', 'IS', '+354', 'isl', 'Europe', NULL, NULL),
(75, 'India', 'IN', '+91', 'hin', 'Asia', NULL, NULL),
(76, 'Indonesia', 'ID', '+62', 'ind', 'Asia', NULL, NULL),
(77, 'Iran', 'IR', '+98', 'fas', 'Asia', NULL, NULL),
(78, 'Iraq', 'IQ', '+964', 'ara', 'Asia', NULL, NULL),
(79, 'Ireland', 'IE', '+353', 'eng', 'Europe', NULL, NULL),
(80, 'Israel', 'IL', '+972', 'heb', 'Asia', NULL, NULL),
(81, 'Italy', 'IT', '+39', 'ita', 'Europe', NULL, NULL),
(82, 'Jamaica', 'JM', '+1', 'eng', 'North America', NULL, NULL),
(83, 'Japan', 'JP', '+81', 'jpn', 'Asia', NULL, NULL),
(84, 'Jordan', 'JO', '+962', 'ara', 'Asia', NULL, NULL),
(85, 'Kazakhstan', 'KZ', '+7', 'kaz', 'Asia', NULL, NULL),
(86, 'Kenya', 'KE', '+254', 'eng', 'Africa', NULL, NULL),
(87, 'Kiribati', 'KI', '+686', 'eng', 'Oceania', NULL, NULL),
(88, 'Korea, North', 'KP', '+850', 'kor', 'Asia', NULL, NULL),
(89, 'Korea, South', 'KR', '+82', 'kor', 'Asia', NULL, NULL),
(90, 'Kuwait', 'KW', '+965', 'ara', 'Asia', NULL, NULL),
(91, 'Kyrgyzstan', 'KG', '+996', 'kir', 'Asia', NULL, NULL),
(92, 'Laos', 'LA', '+856', 'lao', 'Asia', NULL, NULL),
(93, 'Latvia', 'LV', '+371', 'lav', 'Europe', NULL, NULL),
(94, 'Lebanon', 'LB', '+961', 'ara', 'Asia', NULL, NULL),
(95, 'Lesotho', 'LS', '+266', 'sot', 'Africa', NULL, NULL),
(96, 'Liberia', 'LR', '+231', 'eng', 'Africa', NULL, NULL),
(97, 'Libya', 'LY', '+218', 'ara', 'Africa', NULL, NULL),
(98, 'Liechtenstein', 'LI', '+423', 'deu', 'Europe', NULL, NULL),
(99, 'Lithuania', 'LT', '+370', 'lit', 'Europe', NULL, NULL),
(100, 'Luxembourg', 'LU', '+352', 'fra', 'Europe', NULL, NULL),
(101, 'Madagascar', 'MG', '+261', 'mlg', 'Africa', NULL, NULL),
(102, 'Malawi', 'MW', '+265', 'eng', 'Africa', NULL, NULL),
(103, 'Malaysia', 'MY', '+60', 'msa', 'Asia', NULL, NULL),
(104, 'Maldives', 'MV', '+960', 'div', 'Asia', NULL, NULL),
(105, 'Mali', 'ML', '+223', 'fra', 'Africa', NULL, NULL),
(106, 'Malta', 'MT', '+356', 'mlt', 'Europe', NULL, NULL),
(107, 'Marshall Islands', 'MH', '+692', 'eng', 'Oceania', NULL, NULL),
(108, 'Mauritania', 'MR', '+222', 'ara', 'Africa', NULL, NULL),
(109, 'Mauritius', 'MU', '+230', 'eng', 'Africa', NULL, NULL),
(110, 'Mexico', 'MX', '+52', 'spa', 'North America', NULL, NULL),
(111, 'Micronesia', 'FM', '+691', 'eng', 'Oceania', NULL, NULL),
(112, 'Moldova', 'MD', '+373', 'ron', 'Europe', NULL, NULL),
(113, 'Monaco', 'MC', '+377', 'fra', 'Europe', NULL, NULL),
(114, 'Mongolia', 'MN', '+976', 'mon', 'Asia', NULL, NULL),
(115, 'Montenegro', 'ME', '+382', 'srp', 'Europe', NULL, NULL),
(116, 'Morocco', 'MA', '+212', 'ara', 'Africa', NULL, NULL),
(117, 'Mozambique', 'MZ', '+258', 'por', 'Africa', NULL, NULL),
(118, 'Myanmar', 'MM', '+95', 'mya', 'Asia', NULL, NULL),
(119, 'Namibia', 'NA', '+264', 'eng', 'Africa', NULL, NULL),
(120, 'Nauru', 'NR', '+674', 'eng', 'Oceania', NULL, NULL),
(121, 'Nepal', 'NP', '+977', 'nep', 'Asia', NULL, NULL),
(122, 'Netherlands', 'NL', '+31', 'nld', 'Europe', NULL, NULL),
(123, 'New Zealand', 'NZ', '+64', 'eng', 'Oceania', NULL, NULL),
(124, 'Nicaragua', 'NI', '+505', 'spa', 'North America', NULL, NULL),
(125, 'Niger', 'NE', '+227', 'fra', 'Africa', NULL, NULL),
(126, 'Nigeria', 'NG', '+234', 'eng', 'Africa', NULL, NULL),
(127, 'North Macedonia', 'MK', '+389', 'mkd', 'Europe', NULL, NULL),
(128, 'Norway', 'NO', '+47', 'nor', 'Europe', NULL, NULL),
(129, 'Oman', 'OM', '+968', 'ara', 'Asia', NULL, NULL),
(130, 'Pakistan', 'PK', '+92', 'urd', 'Asia', NULL, NULL),
(131, 'Palau', 'PW', '+680', 'eng', 'Oceania', NULL, NULL),
(132, 'Panama', 'PA', '+507', 'spa', 'North America', NULL, NULL),
(133, 'Papua New Guinea', 'PG', '+675', 'eng', 'Oceania', NULL, NULL),
(134, 'Paraguay', 'PY', '+595', 'spa', 'South America', NULL, NULL),
(135, 'Peru', 'PE', '+51', 'spa', 'South America', NULL, NULL),
(136, 'Philippines', 'PH', '+63', 'fil', 'Asia', NULL, NULL),
(137, 'Poland', 'PL', '+48', 'pol', 'Europe', NULL, NULL),
(138, 'Portugal', 'PT', '+351', 'por', 'Europe', NULL, NULL),
(139, 'Qatar', 'QA', '+974', 'ara', 'Asia', NULL, NULL),
(140, 'Romania', 'RO', '+40', 'ron', 'Europe', NULL, NULL),
(141, 'Russia', 'RU', '+7', 'rus', 'Europe', NULL, NULL),
(142, 'Rwanda', 'RW', '+250', 'kin', 'Africa', NULL, NULL),
(143, 'Saint Kitts and Nevis', 'KN', '+1', 'eng', 'North America', NULL, NULL),
(144, 'Saint Lucia', 'LC', '+1', 'eng', 'North America', NULL, NULL),
(145, 'Saint Vincent and the Grenadines', 'VC', '+1', 'eng', 'North America', NULL, NULL),
(146, 'Samoa', 'WS', '+685', 'eng', 'Oceania', NULL, NULL),
(147, 'San Marino', 'SM', '+378', 'ita', 'Europe', NULL, NULL),
(148, 'Sao Tome and Principe', 'ST', '+239', 'por', 'Africa', NULL, NULL),
(149, 'Saudi Arabia', 'SA', '+966', 'ara', 'Asia', NULL, NULL),
(150, 'Senegal', 'SN', '+221', 'fra', 'Africa', NULL, NULL),
(151, 'Serbia', 'RS', '+381', 'srp', 'Europe', NULL, NULL),
(152, 'Seychelles', 'SC', '+248', 'eng', 'Africa', NULL, NULL),
(153, 'Sierra Leone', 'SL', '+232', 'eng', 'Africa', NULL, NULL),
(154, 'Singapore', 'SG', '+65', 'eng', 'Asia', NULL, NULL),
(155, 'Slovakia', 'SK', '+421', 'slk', 'Europe', NULL, NULL),
(156, 'Slovenia', 'SI', '+386', 'slv', 'Europe', NULL, NULL),
(157, 'Solomon Islands', 'SB', '+677', 'eng', 'Oceania', NULL, NULL),
(158, 'Somalia', 'SO', '+252', 'som', 'Africa', NULL, NULL),
(159, 'South Africa', 'ZA', '+27', 'eng', 'Africa', NULL, NULL),
(160, 'South Sudan', 'SS', '+211', 'eng', 'Africa', NULL, NULL),
(161, 'Spain', 'ES', '+34', 'spa', 'Europe', NULL, NULL),
(162, 'Sri Lanka', 'LK', '+94', 'sin', 'Asia', NULL, NULL),
(163, 'Sudan', 'SD', '+249', 'ara', 'Africa', NULL, NULL),
(164, 'Suriname', 'SR', '+597', 'nld', 'South America', NULL, NULL),
(165, 'Sweden', 'SE', '+46', 'swe', 'Europe', NULL, NULL),
(166, 'Switzerland', 'CH', '+41', 'deu', 'Europe', NULL, NULL),
(167, 'Syria', 'SY', '+963', 'ara', 'Asia', NULL, NULL),
(168, 'Taiwan', 'TW', '+886', 'zho', 'Asia', NULL, NULL),
(169, 'Tajikistan', 'TJ', '+992', 'tgk', 'Asia', NULL, NULL),
(170, 'Tanzania', 'TZ', '+255', 'swa', 'Africa', NULL, NULL),
(171, 'Thailand', 'TH', '+66', 'tha', 'Asia', NULL, NULL),
(172, 'Timor-Leste', 'TL', '+670', 'por', 'Asia', NULL, NULL),
(173, 'Togo', 'TG', '+228', 'fra', 'Africa', NULL, NULL),
(174, 'Tonga', 'TO', '+676', 'ton', 'Oceania', NULL, NULL),
(175, 'Trinidad and Tobago', 'TT', '+1', 'eng', 'North America', NULL, NULL),
(176, 'Tunisia', 'TN', '+216', 'ara', 'Africa', NULL, NULL),
(177, 'Turkey', 'TR', '+90', 'tur', 'Asia', NULL, NULL),
(178, 'Turkmenistan', 'TM', '+993', 'tuk', 'Asia', NULL, NULL),
(179, 'Tuvalu', 'TV', '+688', 'eng', 'Oceania', NULL, NULL),
(180, 'Uganda', 'UG', '+256', 'eng', 'Africa', NULL, NULL),
(181, 'Ukraine', 'UA', '+380', 'ukr', 'Europe', NULL, NULL),
(182, 'United Arab Emirates', 'AE', '+971', 'ara', 'Asia', NULL, NULL),
(183, 'United Kingdom', 'GB', '+44', 'eng', 'Europe', NULL, NULL),
(184, 'United States', 'US', '+1', 'eng', 'North America', NULL, NULL),
(185, 'Uruguay', 'UY', '+598', 'spa', 'South America', NULL, NULL),
(186, 'Uzbekistan', 'UZ', '+998', 'uzb', 'Asia', NULL, NULL),
(187, 'Vanuatu', 'VU', '+678', 'eng', 'Oceania', NULL, NULL),
(188, 'Vatican City', 'VA', '+379', 'ita', 'Europe', NULL, NULL),
(189, 'Venezuela', 'VE', '+58', 'spa', 'South America', NULL, NULL),
(190, 'Vietnam', 'VN', '+84', 'vie', 'Asia', NULL, NULL),
(191, 'Yemen', 'YE', '+967', 'ara', 'Asia', NULL, NULL),
(192, 'Zambia', 'ZM', '+260', 'eng', 'Africa', NULL, NULL),
(193, 'Zimbabwe', 'ZW', '+263', 'eng', 'Africa', NULL, NULL);
COMMIT;
